/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Activation */

#ifndef _Included_com_smk_activate_Activation
#define _Included_com_smk_activate_Activation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Activation
 * Method:    activate
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_smk_activate_Activation_activate
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
