/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Activation.h"
#include <stdbool.h>
#include <string.h>
#include <math.h>

/*
 * Class:     com_smk_activate_Activation
 * Method:    getGrant
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_com_smk_activate_Activation_activate
  (JNIEnv *env, jclass thisClass, jlong code, jlong timeStamp){
  		
  		//const char *str_code= (*env)->GetStringUTFChars(env,code,0);

      long long_time =  ((long) timeStamp) / 3600;

      //const char *str_timestemp= (*env)->GetStringUTFChars(env,long_time,0);
      long long_code = (long) code;
  		
      if(long_time == long_code)
          return true;


	  	return false;



}