/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ignite_mm_ticketing_application_SecureKey */

#ifndef _Included_com_ignite_mm_ticketing_application_SecureKey
#define _Included_com_ignite_mm_ticketing_application_SecureKey
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getGrant
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getGrant
  (JNIEnv *, jclass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getId
  (JNIEnv *, jclass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getKey
  (JNIEnv *, jclass);


/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getScope
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getScope
  (JNIEnv *, jclass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getState
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getState
  (JNIEnv *env, jclass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getPEMKey
  (JNIEnv *env, jclass thisClass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getAESKey
  (JNIEnv *env, jclass thisClass);

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getIV
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getIV
  (JNIEnv *env, jclass thisClass);

#ifdef __cplusplus
}
#endif
#endif
