/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SecureParam */
#include <iostream>
#include <sstream>

#ifndef _Included_com_ignite_mm_ticketing_application_SecureParam
#define _Included_com_ignite_mm_ticketing_application_SecureParam


using namespace std;


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SecureParam
 * Method:    getAccessTokenParam
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getAccessTokenParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);


JNIEXPORT jstring JNICALL
        Java_com_ignite_mm_ticketing_application_SecureParam_getInvoices(JNIEnv *, jobject,
                                                                         jstring,
                                                                         jstring,
                                                                         jstring,
                                                                         jstring);

/*
 * Class:     SecureParam
 * Method:    getSeatPlanParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getSeatPlanParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getTripsParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getTripsParam
        (JNIEnv *, jobject, jstring, jstring);
//JNIEXPORT jstring JNICALL
//        Java_com_ignite_mm_ticketing_application_SecureParam_getOutstandingBooking(JNIEnv *env,
//                                                                                   jclass type,
//                                                                                   jstring token_,
//                                                                                   jstring agent_code_no_,
//                                                                                   jstring date_type_,
//                                                                                   jstring end_date_
//);
JNIEXPORT jstring JNICALL
        Java_com_ignite_mm_ticketing_application_SecureParam_getOutstandingBooking(JNIEnv *env,
                                                                                   jclass type,
                                                                                   jstring token_,
                                                                                   jstring agent_code_no_,
                                                                                   jstring date_type_,
                                                                                   jstring end_date_,
                                                                                   jstring offset,
                                                                                   jstring limit);
/*
 * Class:     SecureParam
 * Method:    getTimesParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT
jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getTimesParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    postSaleParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_postSaleParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring,
         jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);


/*
 * Class:     SecureParam
 * Method:    postSaleConfirmParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_postSaleConfirmParam(
        JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring,
        jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    deleteSaleOrderParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_deleteSaleOrderParam
        (JNIEnv *, jobject, jstring);

/*
* Class:     SecureParam
* Method:    deleteAllOrderParam
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_deleteAllOrderParam
        (JNIEnv *, jobject, jstring);

/*
* Class:     com_ignite_mm_ticketing_application_SecureParam
* Method:    deleteOrderItemParam
* Signature: ()Ljava/lang/String;
*/
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_deleteOrderItemParam
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getAllAgent
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getAllAgentParam
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getBookingOrder
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getBookingOrderParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    editSeatInfoParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_editSeatInfoParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    deleteTicketParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_deleteTicketParam
        (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getOperatorGroupUserParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getOperatorGroupUserParam
        (JNIEnv *, jobject, jstring, jstring);

/* Class:     SecureParam
 * Method:    getExtraDestinationParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getExtraDestinationParam
        (JNIEnv *, jobject, jstring);

/*
 * Class:     SecureParam
 * Method:    getNotiBookingParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getNotiBookingParam
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getCitybyOperatorParam
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getCitybyOperatorParam
        (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     SecureParam
 * Method:    getTimebyOperatorParam
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL
        Java_com_ignite_mm_ticketing_application_SecureParam_getSales(JNIEnv *env, jclass type,
                                                                      jstring accesstoken_,
                                                                      jstring agent_code_no_,
                                                                      jstring start_date_,
                                                                      jstring end_date_, jstring date_type_,
                                                                      jstring offset_, jstring limit_);


        JNIEXPORT jstring JNICALL
Java_com_ignite_mm_ticketing_application_SecureParam_getInvoiceDetail(JNIEnv *env, jclass type,
                                                                      jstring access_token_,
                                                                      jstring invoice_id_);



JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureParam_getTimebyOperatorParam
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
