/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "SecureKey.h"

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getGrant
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getGrant
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "password");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getId
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "721689");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getKey
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "onlineSale@EasyTickeTadmiM");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getScope
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getScope
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "sale,booking");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getState
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getState
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "123456789");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getPEMKey
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCHPKW5c+4I0xfCURdOgAjdoXvh MhXPR8dMs3mOHsDolG8nmdnnETV2yw1x8ol8KsGl6p4D6+tQEYmaqdvhpc6xWCAU HxQRSXnKWvoJNIgtF4J98WaFy1Xdys6tx1GbsM1/ng5FJT2sRypETWDNwePn3UId NvoKCu68i0G9/n61twIDAQAB");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getAESKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getAESKey
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "dYzxXzu8MYyWyhEDawCumvhegFQquPwj");
}

/*
 * Class:     com_ignite_mm_ticketing_application_SecureKey
 * Method:    getIV
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ignite_mm_ticketing_application_SecureKey_getIV
  (JNIEnv *env, jclass thisClass){
	  return (*env)->NewStringUTF(env, "ERCFECX6L3YOBQXU");
}